build:
    config:
        end_year: 2013
        span: 5
        start_year: 2009
    dependencies: {}
    sources:
        table_map: http://www2.census.gov/acs{end_year}_{span}yr/summaryfile/Sequence_Number_and_Table_Number_Lookup.txt
    templates:
        large: '{state}/All_Geographies_Not_Tracts_Block_Groups/{end_year}{span}{lc_utstab}{seg_4}000.zip'
        root: http://www2.census.gov/acs{end_year}_{span}yr/summaryfile/{start_year}-{end_year}_ACSSF_By_State_By_Sequence_Table_Subset/
        small: '{state}/Tracts_Block_Groups_Only/{end_year}{span}{lc_utstab}{seg_4}000.zip'
dependencies:
    geo-p5ye2013: census.gov-acs-geo-p5ye2013-geofile
extract: {}
sources:
    table_meta:
        description: Table metadata, from CensusReporter
        url: https://raw.githubusercontent.com/censusreporter/census-table-metadata/master/precomputed/acs2013_5yr/census_table_metadata.csv
    column_meta:
        description: Column metadata, from CensusReporter
        url: https://raw.githubusercontent.com/censusreporter/census-table-metadata/master/precomputed/acs2013_5yr/census_column_metadata.csv
    table_map:
        description: CSV file of columns and offsets
        url: http://www2.census.gov/acs{end_year}_{span}yr/summaryfile/Sequence_Number_and_Table_Number_Lookup.txt
views: {}
