build:
    dependencies: {}
    geoschemaFile: meta/geoschema.csv
    statesFile: meta/states.yaml
    urls:
        20105: http://www2.census.gov/acs2010_5yr/summaryfile/2006-2010_ACSSF_All_In_2_Giant_Files(Experienced-Users-Only)/2010_ACS_Geography_Files.zip
dependencies: {}
extract: {}
views: {}
