build:
    combined_types:
        counties: null
    dependencies: {}
    requirements:
        geoid: git+https://github.com/CivicKnowledge/geoid.git
    state_url_template: http://www2.census.gov/geo/tiger/TIGER2012/{type}/tl_{year4}_{state:02}_{typelc}.zip
    url_codes:
        BG: blockgroups
        COUNTY: counties
        PLACE: places
        STATE: states
        TRACT: tracts
    us_url_template: http://www2.census.gov/geo/tiger/TIGER2012/{type}/tl_{year4}_us_{typelc}.zip
dependencies:
    states: census.gov-2010_population-geo-orig-geofile-40
extract: {}
views: {}
