about:
    access: public
    footnote: null
    grain: null
    groups: null
    license: ckdbl
    processed: null
    remote: census
    rights: public
    source: null
    space: US
    subject: null
    summary: Column names and positions for the fixed-width geofiles
    tags: []
    time: 2009/2014
    title: ACS Geofile Schema Definitions
contacts:
    wrangler:
        email: eric@sandiegodata.org
        name: Eric Busboom
        url: http://www.sandiegodata.org
dependencies: {}
external_documentation:
    d20091td:
        title: '2009: The 2008-2009 ACS 1-Year Summary File Technical Documentation '
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2009/documentation/1_year/ACS_2009_SF_Tech_Doc.pdf
    d20093td:
        title: '2009: The 2007-2009 ACS 3-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2009/documentation/3_year/ACS_2007-2009_SF_Tech_Doc.pdf
    d20095td:
        title: '2009: The 2005-2009 ACS 5-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2009/documentation/5_year/ACS_2005-2009_SF_Tech_Doc.pdf
    d20101td:
        title: '2010: The 2010-2010  ACS 1-Year Summary File Technical Documentation '
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2010/documentation/1_year/ACS_2010_SF_Tech_Doc.pdf
    d20103td:
        title: '2010: The 2008-2010  ACS 3-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2010/documentation/3_year/ACS_2008-2010_SF_Tech_Doc.pdf
    d20105td:
        title: '2010: The 2006-2010 ACS 5-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2010/documentation/5_year/ACS_2006-2010_SF_Tech_Doc.pdf
    d20111td:
        title: '2011: The 2007-2011 ACS 1-Year Summary File Technical Documentation '
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2011/documentation/1_year/ACS_2011_SF_Tech_Doc.pdf
    d20113td:
        title: '2011: The 2007-2011 ACS 3-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2011/documentation/3_year/ACS_2009-2011_SF_Tech_Doc.pdf
    d20115td:
        title: '2011: The 2007-2011 ACS 5-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2011/documentation/5_year/ACS_2007-2011_SF_Tech_Doc.pdf
    d20121td:
        title: '2012: The 2011-2012 ACS 1-Year Summary File Technical Documentation '
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2012/documentation/1_year/ACS_2012_SF_Tech_Doc.pdf
    d20123td:
        title: '2012: The 2010-2012 ACS 3-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2012/documentation/3_year/ACS_2010-2012_SF_Tech_Doc.pdf
    d20125td:
        title: '2012: The 2008-2012 ACS 5-Year Summary File Technical Documentation'
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2012/documentation/5_year/ACS_2008-2012_SF_Tech_Doc.pdf
    d2013main:
        title: 2013 Documentation Page
        url: https://www.census.gov/programs-surveys/acs/technical-documentation/summary-file-documentation.2013.html
    d2013td:
        title: 2013 ACS Summary File Technical Documentation
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2013/documentation/tech_docs/2013_SummaryFile_Tech_Doc.pdf
    d2014main:
        title: '2014 Documentation Page '
        url: https://www.census.gov/programs-surveys/acs/technical-documentation/summary-file-documentation.2014.html
    d2014td:
        title: 2014 ACS Summary File Technical Documentation
        url: http://www2.census.gov/programs-surveys/acs/summary_file/2014/documentation/tech_docs/2014_SummaryFile_Tech_Doc.pdf
identity:
    btime: 2009e
    dataset: acs_geofile
    id: d04s
    revision: 4
    source: census.gov
    subset: schemas
    version: 0.0.4
names:
    fqname: census.gov-acs_geofile-schemas-2009e-0.0.4~d04s004
    name: census.gov-acs_geofile-schemas-2009e
    vid: d04s004
    vname: census.gov-acs_geofile-schemas-2009e-0.0.4
pipelines:
    build:
        first:
        - RemoveBlankColumns
        - Delete(['releases'])
        - Nullify
        select_partition:
        - SelectPartition("dict(time=str(source.time), grain=source.grain, table=source.dest_table_name)")
    build-table_shells:
        first:
        - Delete(['year', 'releases'])
        - RemoveBlankColumns
        - Nullify
        last:
        - ambry.etl.Skip('skip_empty_table_id')
        select_partition:
        - SelectPartition("dict(time=str(source.time), grain=source.grain, table=source.dest_table_name)")
requirements:
    OpenSSL: PyOpenSSL
    gdata: gdata
    gspread: gspread
    oauth2client: oauth2client
versions: {}
